# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular CI

on:
  push:
    # Remove "SSW-55-git-ci-cd-pipeline" later, currently included for testing
    branches: [ "main", "SSW-55-git-ci-cd-pipeline" ]
  pull_request:
    branches: [ "main", "SSW-55-git-ci-cd-pipeline" ]

defaults:
  run:
    working-directory: ./dhbw-study-smart-frontend

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './dhbw-study-smart-frontend/package-lock.json'
    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - run: npm test
